import { Game } from "src/components/Game";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>tic-toc-toe</title>
        <meta name="description" content="Generated by create next app" />
      </Head> */}
      <Game />
      <footer className={styles.footer}></footer>
    </div>
  );
}
